import { Outfit as OutfitFont, Ovo as OvoFont } from "next/font/google";
import "./globals.css";

const outfit = OutfitFont({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Ensure these weights are supported
});

const ovo = OvoFont({
  subsets: ["latin"],
  weight: ["400"], // Ovo only supports 400
});

export const metadata = {
  title: "Virendra's Profile",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${outfit.className} antialiased leading-8 overflow-x-hidden dark:bg-darkTheme `}
      >
        {children}
      </body>
    </html>
  );
}
